services:
  ct-postgresql:
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    env_file:
      - .env
    environment:
      - POSTGRESQL_USERNAME=${DATABASE_USER}
      - POSTGRESQL_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRESQL_DATABASE=${DATABASE_DB_NAME}
