name: Build CI

on:
  push:
    branches:
      - main
jobs:
  jb-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Using Node.js LTS Version
        uses: actions/setup-node@v3
        with:
          node-version: 22.

      - name: Install Dependencies
        run: |
          npm install -g pnpm
          pnpm install

      - name: Check lint and type
        run: pnpm check
